sonar.projectKey=Timeo10_tp-pipeline-securiser
sonar.organization=timeo10

# ton code est à la racine
sonar.sources=.
sonar.tests=.

# fichiers de test
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# exclusions importantes
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.github/**,**/public/**,**/bin/**

# couverture Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
